name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'  # Run on any branch push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sintosunny1008
          password: dckr_pat_0h8K5DMbm8YVRXhk3INoN-kg_So

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            sintosunny/flutter-web-app:latest
            sintosunny/flutter-web-app:${{ github.sha }}
