name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'  # Run on any branch push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO_NAME: "294619603110.dkr.ecr.ap-southeast-2.amazonaws.com/demo_push_testaction"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            sintosunny1008/flutter-web-app:latest
            sintosunny1008/flutter-web-app:${{ github.sha }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-2"

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag and Push Docker Image to AWS ECR
        run: |
          echo "#### Tagging and Pushing Image To ECR ####"
          IMAGE_TAG=${{ github.sha }}
          IMAGE_URI=${DOCKER_REPO_NAME}:${IMAGE_TAG}
          LATEST_URI=${DOCKER_REPO_NAME}:latest

          # Tag the Docker image for ECR
          docker tag sintosunny1008/flutter-web-app:${{ github.sha }} $IMAGE_URI
          docker tag sintosunny1008/flutter-web-app:latest $LATEST_URI

          # Push to ECR
          echo "Pushing $IMAGE_URI"
          docker push $IMAGE_URI
          echo "Pushing $LATEST_URI"
          docker push $LATEST_URI
