name: Application Build

on:
  push:
    branches:
      - master
      - uat
      - staging

jobs:
  Build:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO_NAME: "294619603110.dkr.ecr.ap-southeast-2.amazonaws.com/demo_push_testaction"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Genrate secrets JSON file
        run: |
          echo '${{ github.ref_name }}'
          echo "Generating secrets.json file"
          echo '${{ secrets.SECRETS_JSON }}' | jq '.' > secrets.json

      - name: Set Image Tag
        run: |
          IMAGE_TAG="${{ github.ref_name }}-${{ github.run_number }}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build Image
        run: |
          docker build -t $DOCKER_REPO_NAME:$IMAGE_TAG .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag and Push Docker Image to AWS ECR
        run: |
          echo "#### Pushing Image To ECR ####"
          docker push $DOCKER_REPO_NAME:$IMAGE_TAG
